language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_script:
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
  - composer --dev install 

script: phpunit --configuration phpunit.xml.dist
